"""Refactor models into separate files

Revision ID: 7c98ebbec651
Revises: 200846c41948
Create Date: 2023-08-24 13:31:23.442307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c98ebbec651'
down_revision: Union[str, None] = '200846c41948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roaster', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('roast_level', sa.String(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coffees_date_received'), ['date_received'], unique=False)
        batch_op.create_index(batch_op.f('ix_coffees_roast_level'), ['roast_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_coffees_roaster'), ['roaster'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_rating'), ['rating'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_rating'))

    op.drop_table('ratings')
    op.drop_table('users')
    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coffees_roaster'))
        batch_op.drop_index(batch_op.f('ix_coffees_roast_level'))
        batch_op.drop_index(batch_op.f('ix_coffees_date_received'))

    op.drop_table('coffees')
    # ### end Alembic commands ###
